# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = LiveStreamCam
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"." \
    -lopencv_world451d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(LiveStreamCam.pri)
win32:RC_FILE = LiveStreamCam.rc
